### ISSUE TITLE
"Enter Zone" message appearing too often

### ISSUE THREAD

**Issue by Everett4God** [SkyeRangerDelta/BlueMap-Zones#1]
Issue when going back and forth between zones/coming in and out of the Nether. Need to find ways to prevent message from triggering too often. Potential fix could be implementing a command for individual users to disable zone notifications. Alternatively, being able to toggle the full-screen pop up into a small chat readout with a different sound could help. Potentially could add multiple types of pings, configurable via commands per user.

**Comment by SkyeRangerDelta** [comment]
- [x] Introduce client-side toggle enabled
- [x] Introduce client-side type toggle

**Comment by SkyeRangerDelta** [comment]
Completed with e2ec370d43eea08a9b67a6783d733980f23c7728
